AI_Datascience_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path("", include('main.urls')),
]


handler404 = 'main.views.show404'

main/urls.py
from django.urls import path
from . import views


app_name = 'main'


urlpatterns = [
    path("", views.showdasboard, name="dashboard"),
    path("about/", views.showabout, name="about"),
    path("projects/", views.showproject, name="projects"),
    path("upcoming_events/", views.showevents, name="events"),
    path("contact_us/", views.showcontact, name="contact_us"),
    path("team/", views.showteam, name="team"),
    path("blog/", views.showBlog, name="blog"),
    path("faq/", views.showfaq, name="faq"),
     path("presidents_corner/",views.showpresidents_corner,name="presidents_corner"),
]

main/models.py
from django.db import models

# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=255, null=True)
    cotent = models.TextField(null=True)
    date_created = models.DateField(auto_now_add=True)
    writer = models.CharField(max_length=255, null=True)
    image = models.ImageField(null=True, blank=True, upload_to="blog/")

    

class Events(models.Model):
    title = models.CharField(max_length=255, null=True)
    about = models.TextField(null=True)
    date = models.DateTimeField(null=True)
    image = models.ImageField(null=True, blank=True, upload_to="events/")

main/views.py
from django.shortcuts import render

# Create your views here.

def showdasboard(request):
    context = {
        "activedash":True
    }
    return render(request,'main/dashboard.html',context)

def showabout(request):
    context = {
        "activeabout":True
    }
    return render(request, 'main/about_us.html',context)
    

def showproject(request):
    context = {
        "activeproject":True
    }
    return render(request, 'main/projects.html',context)
    
    
def showevents(request):
    context = {
        "activeevent":True
    }
    return render(request, 'main/events.html',context)
    

    
def showcontact(request):
    context = {
        "activecontact":True
    }
    return render(request, 'main/contact_us.html',context)
    

def showteam(request):
    context = {
        "activeabout":True
    }
    return render(request, 'main/ourteam.html',context)

def showpresidents_corner(request):
    context = {
        "activeabout":True
    }
    return render(request, 'main/presidents_corner.html',context)
    
def showfaq(request):
    context = {
        "activeexplore":True
    }
    return render(request, 'main/faq.html', context)
    
def show404(request, exception):
    return render (request,'main/404.html',status=404)


def showBlog(request):
    return render (request,'main/blog.html')

AI_Datascience_website/templates/layout/layout.html
<!DOCTYPE html>
<html lang="en">

{%load static%}
<head>
    <meta charset="utf-8">
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo.png'%}">
    <title> KNUST AI/Data Science Club</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Ubuntu:wght@500;700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" style="width: 3rem; height: 3rem;" role="status">
            
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <div class="container-fluid sticky-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark p-0">
              
                <a href="{% url 'main:dashboard'%}" class="navbar-brand">
                   
                    <div class="img-logo"  style="background-color: white;border-radius: 100%; width: 60px; height: 60px; display: flex;justify-content: center;align-items: center; margin-right: 10px;">
                        <img width="50px" height="50px" src="{% static 'img/logo.png' %}">
                    </div>
                </a>
                <button type="button" class="navbar-toggler ms-auto me-0" data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto">
                        <a   href="{% url 'main:dashboard'%}" class="nav-item nav-link {% if activedash %}active {%endif%}">Home</a>
                       
                           <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle {% if activeabout %}active {%endif%}" data-bs-toggle="dropdown">About Us</a>
                            <div class="dropdown-menu bg-light mt-2">
                                
                                      <a href="{% url 'main:presidents_corner'%}" class="dropdown-item">Presidents Corner</a>
                                <a  href="{% url 'main:about'%}"class="dropdown-item">Mission and Vision</a>
                                <a href="{% url 'main:team' %}" class="dropdown-item">Our Team</a>
                              
                               
                                
                            </div>
                        </div>
                        <a href="{% url 'main:events'%}"class="nav-item nav-link {% if activeevent %}active {%endif%}">Events</a>
                        <a href="{% url 'main:projects'%}" class="nav-item nav-link {% if activeproject %}active {%endif%}">Projects</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle {% if activeexplore%}active {%endif%}" data-bs-toggle="dropdown">Explore</a>
                            <div class="dropdown-menu bg-light mt-2">
                                
                                      <a href="{% url 'main:blog'%}" class="dropdown-item">Blog</a>
                                      <!--
                                <a href="{% url 'main:team'%}" class="dropdown-item">Our Team</a>
                            
                                -->
                              
                                <a href="{% url 'main:faq' %}" class="dropdown-item">FAQs</a>
                                
                            </div>
                        </div>
                        <a href="{% url 'main:contact_us'%}" class="nav-item nav-link {% if activecontact%}active {%endif%}">Contact Us </a>
                    </div>
                    
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->

{%block body%}
{%endblock%}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.1s">
                    <a href="{% url 'main:dashboard'%}" class="d-inline-block mb-3">
                        <div class="img-logo"  style="background-color: white;border-radius: 100%; width: 60px; height: 60px; display: flex;justify-content: center;align-items: center; margin-right: 10px;">
                            <img width="50px" height="50px" src="{% static 'img/logo.png' %}">
                        </div>
                    </a>
                    <p class="mb-0">Join a Dynamic Environment, Focused on Unleashing Creativity, Building Skills, and Making a Difference in the World of AI and Data Science.</p>
                </div>
                <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.3s">
                    <h5 class="text-white mb-4">Get In Touch</h5>
                  
                    <p><i class="fa fa-phone-alt me-3"></i>+233 
                        0558232578</p>
                    <p><i class="fa fa-envelope me-3"></i>aidatascience988@gmail.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href="https://x.com/ai_knust?s=21" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" target="_blank" href="https://web.facebook.com/groups/389673286819920/"><i class="fab fa-facebook-f"></i></a>

                    </div>
                </div>
                <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.5s">
                    <h5 class="text-white mb-4">Popular Link</h5>
                    <a class="btn btn-link" href="{% url 'main:about'%}">About Us</a>
                    <a class="btn btn-link" href="{% url 'main:contact_us'%}">Contact Us</a>
                    <a class="btn btn-link" href="{% url 'main:faq'%}">FAQ</a>
                   
                </div>
             
            </div>
        </div>
        <div class="container wow fadeIn" data-wow-delay="0.1s">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">KNUST AI/Data Sceince Club</a>, All Right Reserved.

                    </div>
              
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top pt-2"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.j' %}s"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

main/templates/main/about_us.html
{%extends 'layout/layout.html'%}
{%load static%}
{% block body%}
    <!-- Hero Start -->
    <div class="container-fluid pt-5 bg-primary hero-header">
        <div class="container pt-5">
            <div class="row g-5 pt-5">
                <div class="col-lg-6 align-self-center text-center text-lg-start mb-lg-5">
                    <h1 class="display-4 text-white mb-4 animated slideInRight">About Us</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center justify-content-lg-start mb-0">
                            <li class="breadcrumb-item"><a class="text-white" href="{% url 'main:dashboard'%}">Home</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">About Us</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 align-self-end text-center text-lg-end">
                    <img class="img-fluid" src="{% static 'img/hero-img.png' %}" alt="" style="max-height: 300px;">
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Full Screen Search Start -->
    <div class="modal fade" id="searchModal" tabindex="-1">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content" style="background: rgba(20, 24, 62, 0.7);">
                <div class="modal-header border-0">
                    <button type="button" class="btn btn-square bg-white btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex align-items-center justify-content-center">
                    <div class="input-group" style="max-width: 600px;">
                        <input type="text" class="form-control bg-transparent border-light p-3"
                            placeholder="Type search keyword">
                        <button class="btn btn-light px-4"><i class="bi bi-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Full Screen Search End -->


       <!-- About Start -->
       <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5 align-items-center">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <div class="about-img">
                        <img class="img-fluid" src="{% static 'img/about-img.jpeg' %}">
                    </div>
                </div>
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                    <div class="btn btn-sm border rounded-pill text-primary px-3 mb-3">About Us</div>
                    <h1 class="mb-4">Discover Our Data Science and AI Community</h1>
                    <p class="mb-4">Welcome to KNUST AI/Data Science Club , Our AI/Data Science Club is driven by a collective aspiration to explore the frontiers of artificial intelligence and data science, fostering an environment that promotes learning, innovation, and collaboration. With the exponential growth in Artificial Intelligence in the world today, we believe that establishing this club will not only meet the growing demand for AI and data science knowledge but also provide a platform for students to exchange ideas, hone their skills, and undertake impactful projects.</p>
                    <p class="mb-4">Together, let's push boundaries, innovate, and build a community where curiosity knows no limits.

                        .</p>
                  
                    
                </div>
            </div> <div class="container-fluid bg-light py-5">
                <div class="container py-5">
                    <div class="row g-5 align-items-center">
                        <div class="col-lg-12 wow fadeIn" data-wow-delay="0.1s">
                            <div class="btn btn-sm border rounded-pill text-primary px-3 mb-3">Our Mission </div>
                          
                            <p class="mb-4"><i class="fa fa-check text-primary me-2"></i>
                                Create a vibrant and cooperative community of data science and artificial intelligence enthusiasts who are committed
                                 to furthering the fields of study, practice, and research</p>
                                 <p class="mb-4"><i class="fa fa-check text-primary me-2"></i>
                                    Provide a platform for students to expand their knowledge in AI and data science through workshops, seminars, and hands-on projects, contributing to the academic and research landscape at KNUST.</p>
                                     <p class="mb-4"><i class="fa fa-check text-primary me-2"></i>
                                        Emphasize the importance of appropriate application of data-driven technology and responsible use of AI in all our endeavors, advocating for the ethical use of data and technology</p>
                                         <p class="mb-4"><i class="fa fa-check text-primary me-2"></i>
                                            Foster an inclusive environment that encourages collaboration among students, faculty, and industry experts to exchange ideas and expertise</p>

                        </div>
                        <div class="col-lg-12 wow fadeIn" data-wow-delay="0.1s">
                            <div class="btn btn-sm border rounded-pill text-primary px-3 mb-3">Our Vision</div>
                            
                            <p class="mb-4">At the KNUST AI/Data Science club, our vision is to be the premier
                                 hub for students interested in AI and data science, driving innovation and excellence in these 
                                 fields. We envision a future where our club members are at the forefront of AI and data science 
                                 advancements, leveraging their expertise to make meaningful contributions to technology while upholding 
                                 ethical and responsible practices. Beyond our community, we are dedicated to imparting our knowledge 
                                 to other organizations and enlightening them about the numerous advantages of artificial intelligence 
                                 and data science,
                                 ultimately assisting in their success and the advancement of the society as a whole.</p>
                         
                        </div>
                     
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

{%endblock%}

main/templates/main/blog.html
{%extends 'layout/layout.html'%}
{%load static%}
 
{%block body%}<!-- Hero Start -->
    <div class="container-fluid pt-5 bg-primary hero-header">
        <div class="container pt-5">
            <div class="row g-5 pt-5">
                <div class="col-lg-6 align-self-center text-center text-lg-start mb-lg-5">
                    <h1 class="display-4 text-white mb-4 animated slideInRight">Our Blog Post</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center justify-content-lg-start mb-0">
                            <li class="breadcrumb-item"><a class="text-white" href="{% url 'main:dashboard'%}">Home</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Blog</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 align-self-end text-center text-lg-end">
                    <img class="img-fluid" src="{% static 'img/hero-img.png' %}" alt="" style="max-height: 300px;">
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->




    <!-- Case Start 
    <div class="container-fluid bg-light py-5">
        <div class="container py-5">
            <div class="mx-auto text-center wow fadeIn" data-wow-delay="0.1s" style="max-width: 500px;">
                
                
            </div>
            <div class="row g-4">
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.3s">
                    <div class="case-item position-relative overflow-hidden rounded mb-2">
                        <img class="img-fluid" src="{% static 'img/project-1.jpg' %}" alt="">
                        <a class="case-overlay text-decoration-none" href="">
                            <small>Robotic Automation</small>
                            <h5 class="lh-base text-white mb-3">Lorem elitr magna stet eirmod labore amet labore clita
                            </h5>
                            <span class="btn btn-square btn-primary"><i class="fa fa-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.5s">
                    <div class="case-item position-relative overflow-hidden rounded mb-2">
                        <img class="img-fluid" src="{% static 'img/project-2.jpg' %}" alt="">
                        <a class="case-overlay text-decoration-none" href="">
                            <small>Machine learning</small>
                            <h5 class="lh-base text-white mb-3">Lorem elitr magna stet eirmod labore amet labore clita
                            </h5>
                            <span class="btn btn-square btn-primary"><i class="fa fa-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.7s">
                    <div class="case-item position-relative overflow-hidden rounded mb-2">
                        <img class="img-fluid" src="{% static 'img/project-3.jpg' %}" alt="">
                        <a class="case-overlay text-decoration-none" href="">
                            <small>Predictive Analysis</small>
                            <h5 class="lh-base text-white mb-3">Lorem elitr magna stet eirmod labore amet labore clita
                            </h5>
                            <span class="btn btn-square btn-primary"><i class="fa fa-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
   -->
   <div class="container-fluid bg-light py-5" style="height: 70vh;">
    <div class="container py-5">
        <div class="mx-auto text-center wow fadeIn" data-wow-delay="0.1s" style="max-width: 500px;">
            
            
        </div>
        <div class="row g-4 h-100">
          
        <span>No Blog Post</span>
        </div>
    </div>
</div>
{% endblock%}

main/templates/main/contact_us.html
{%extends 'layout/layout.html'%}
{%load static%}
 
{%block body%}<!-- Hero Start -->
    <div class="container-fluid pt-5 bg-primary hero-header">
        <div class="container pt-5">
            <div class="row g-5 pt-5">
                <div class="col-lg-6 align-self-center text-center text-lg-start mb-lg-5">
                    <h1 class="display-4 text-white mb-4 animated slideInRight">Contact Us </h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center justify-content-lg-start mb-0">
                            <li class="breadcrumb-item"><a class="text-white" href="{% url 'main:dashboard'%}">Home</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Contact Us</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 align-self-end text-center text-lg-end">
                    <img class="img-fluid" src="{% static 'img/hero-img.png' %}" alt="" style="max-height: 300px;">
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->



   
    <!-- About End -->
   <!-- Contact Start -->
   <div class="container-fluid py-5">
    <div class="container py-5">
        <div class="mx-auto text-center wow fadeIn" data-wow-delay="0.1s" style="max-width: 500px;">
            <div class="btn btn-sm border rounded-pill text-primary px-3 mb-3">Contact Us</div>
            <h1 class="mb-4">Please Contact Us</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="d-flex align-items-center justify-content-center my-4 px-3  w-100">
                    <a class="btn btn-outline-primary btn-square me-3" href="mailto: aidatascience988@gmail.com"><i class="fa fa-envelope"></i></a>
                    <a class="btn btn-outline-primary btn-square me-3"  target="_blank" href="https://web.facebook.com/groups/389673286819920/"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-primary btn-square me-3" href="https://x.com/ai_knust?s=21"><svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path fill="#ccd2db" d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zm297.1 84L257.3 234.6 379.4 396H283.8L209 298.1 123.3 396H75.8l111-126.9L69.7 116h98l67.7 89.5L313.6 116h47.5zM323.3 367.6L153.4 142.9H125.1L296.9 367.6h26.3z"/></svg></a>
                   
                </div>
                <p class="text-center mb-4">Have a question, suggestion, or just want to say hello? We'd love to hear from you! </p>
                <div class="wow fadeIn" data-wow-delay="0.3s">
                    <form>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="name" placeholder="Your Name">
                                    <label for="name">Your Name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" class="form-control" id="email" placeholder="Your Email">
                                    <label for="email">Your Email</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="subject" placeholder="Subject">
                                    <label for="subject">Subject</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control" placeholder="Leave a message here" id="message" style="height: 150px"></textarea>
                                    <label for="message">Message</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->

 
{% endblock%}

main/templates/main/events.html
{%extends 'layout/layout.html'%}
{%load static%}
 
{%block body%}<!-- Hero Start -->
    <div class="container-fluid pt-5 bg-primary hero-header">
        <div class="container pt-5">
            <div class="row g-5 pt-5">
                <div class="col-lg-6 align-self-center text-center text-lg-start mb-lg-5">
                    <h1 class="display-4 text-white mb-4 animated slideInRight">Our Upcoming  Events</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center justify-content-lg-start mb-0">
                            <li class="breadcrumb-item"><a class="text-white" href="{% url 'main:dashboard'%}">Home</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Events</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 align-self-end text-center text-lg-end">
                    <img class="img-fluid" src="{% static 'img/hero-img.png' %}" alt="" style="max-height: 300px;">
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->




    <!-- Case Start 
    <div class="container-fluid bg-light py-5">
        <div class="container py-5">
            <div class="mx-auto text-center wow fadeIn" data-wow-delay="0.1s" style="max-width: 500px;">
                
                
            </div>
            <div class="row g-4">
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.3s">
                    <div class="case-item position-relative overflow-hidden rounded mb-2">
                        <img class="img-fluid" src="{% static 'img/project-1.jpg' %}" alt="">
                        <a class="case-overlay text-decoration-none" href="">
                            <small>Robotic Automation</small>
                            <h5 class="lh-base text-white mb-3">Lorem elitr magna stet eirmod labore amet labore clita
                            </h5>
                            <span class="btn btn-square btn-primary"><i class="fa fa-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.5s">
                    <div class="case-item position-relative overflow-hidden rounded mb-2">
                        <img class="img-fluid" src="{% static 'img/project-2.jpg' %}" alt="">
                        <a class="case-overlay text-decoration-none" href="">
                            <small>Machine learning</small>
                            <h5 class="lh-base text-white mb-3">Lorem elitr magna stet eirmod labore amet labore clita
                            </h5>
                            <span class="btn btn-square btn-primary"><i class="fa fa-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 wow fadeIn" data-wow-delay="0.7s">
                    <div class="case-item position-relative overflow-hidden rounded mb-2">
                        <img class="img-fluid" src="{% static 'img/project-3.jpg' %}" alt="">
                        <a class="case-overlay text-decoration-none" href="">
                            <small>Predictive Analysis</small>
                            <h5 class="lh-base text-white mb-3">Lorem elitr magna stet eirmod labore amet labore clita
                            </h5>
                            <span class="btn btn-square btn-primary"><i class="fa fa-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
   -->
   <div class="container-fluid bg-light py-5" style="height: 70vh;">
    <div class="container py-5">
        <div class="mx-auto text-center wow fadeIn" data-wow-delay="0.1s" style="max-width: 500px;">
            
            
        </div>
        <div class="row g-4 h-100">
          
        <span>No Upcoming Events</span>
        </div>
    </div>
</div>
{% endblock%}